"""added artist

Revision ID: 93f890c6a745
Revises: 9a0dd5340383
Create Date: 2023-08-07 17:46:34.958656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f890c6a745'
down_revision = '9a0dd5340383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_artist_user", 'users', ['user_id'], ['id'])

    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('artist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_song_artist', 'artists', ['artist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_constraint("fk_song_artist", type_='foreignkey')
        batch_op.drop_column('artist_id')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_constraint("fk_artist_user", type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
